/*
 * Builds the demo pages in this folder from the real ones next door.
 *
 *     node demo/build-demo.js
 *
 * Each page is copied as-is apart from four changes:
 *   1. demo-mock.js is loaded first, which answers every api/*.php call
 *      from sample data (see that file), and a noindex meta is added.
 *   2. assets/ and logo.png paths gain a ../ so they resolve from demo/.
 *   3. A script redirect to a page outside the demo goes to index.html
 *      instead (e.g. the form builder returning to admin.html after Save).
 *   4. A banner comment saying where the file came from.
 *
 * So the demo always shows the current pages: change a real page, rebuild,
 * and the demo follows. index.html is written by hand and not touched here.
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const OUT = __dirname;

const PAGES = [
  "dashboard.html",
  "forms.html",
  "survey.html",
  "content.html",
  "notifications.html",
  "admin-form-builder.html"
];

const IN_DEMO = new Set(["index.html", ...PAGES]);

for (const page of PAGES) {
  let html = fs.readFileSync(path.join(ROOT, page), "utf8");
  const nl = html.includes("\r\n") ? "\r\n" : "\n";

  const head = html.match(/<head[^>]*>/i);
  if (!head) throw new Error(`${page}: no <head>`);

  const inject = [
    "",
    `<!-- Demo copy of ../${page}, generated by demo/build-demo.js. Edit the real page and rebuild. -->`,
    `<meta name="robots" content="noindex">`,
    `<script src="demo-mock.js"></script>`
  ].join(nl);

  html = html.replace(head[0], head[0] + inject);

  html = html
    .replace(/(["'(])assets\//g, "$1../assets/")
    .replace(/(["'])logo\.png/g, "$1../logo.png");

  html = html.replace(
    /(location\.href\s*=\s*)(["'])([\w-]+\.html)\2/g,
    (match, assign, quote, target) =>
      IN_DEMO.has(target) ? match : `${assign}${quote}index.html${quote}`
  );

  fs.writeFileSync(path.join(OUT, page), html);
  console.log(`demo/${page}`);
}
